services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: rebuild
          path: requirements.txt
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  # ollama:
  #   container_name: ollama
  #   build:
  #     context: .
  #     dockerfile: ./ollama/Dockerfile
  #   volumes:
  #     - ollama:/root/.ollama
  #   ports:
  #     - '11435:11435'
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0:11435
  #     - OLLAMA_NUM_PARALLEL=10 # Number of max allowed requests simultaneously
  #     - OLLAMA_MAX_LOADED_MODELS=4 # Number of max allowed models loaded simultaneously
  #     - gpus=all
  #   pull_policy: always
  #   tty: true
  #   restart: unless-stopped
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]
  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    ports:
      - "80:80"
volumes:
  ollama:
  db:
  dashboard:
