"""init2

Revision ID: 185c84d3b55c
Revises: 4565b9c2dda5
Create Date: 2024-05-27 22:51:57.359058

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '185c84d3b55c'
down_revision = '4565b9c2dda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('findings', 'finding',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('findings', 'finding',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###