"""add task celery id

Revision ID: 7d202c07bc94
Revises: df4b7ee858c9
Create Date: 2024-06-26 20:42:24.958700

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import models


# revision identifiers, used by Alembic.
revision = '7d202c07bc94'
down_revision = 'df4b7ee858c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_task', sa.Column('celery_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_task', 'celery_task_id')
    # ### end Alembic commands ###