"""add cat to finding

Revision ID: 8e2452c67d2d
Revises: cd8d7518de6d
Create Date: 2024-07-19 00:56:13.146332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import db


# revision identifiers, used by Alembic.
revision = '8e2452c67d2d'
down_revision = 'cd8d7518de6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'category')
    # ### end Alembic commands ###