"""aggregated

Revision ID: 9e31625c7978
Revises: 8e2452c67d2d
Create Date: 2024-07-26 08:56:17.779435

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import db


# revision identifiers, used by Alembic.
revision = '9e31625c7978'
down_revision = '8e2452c67d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_recommendations',
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('recommendation_task_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_task_id'], ['recommendation_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings_aggregated_association',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('aggregated_recommendation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aggregated_recommendation_id'], ['aggregated_recommendations.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'aggregated_recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings_aggregated_association')
    op.drop_table('aggregated_recommendations')
    # ### end Alembic commands ###