"""add_more_tables2

Revision ID: c3fdb30822c4
Revises: cefb826a201b
Create Date: 2024-06-11 17:59:48.102377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import models


# revision identifiers, used by Alembic.
revision = 'c3fdb30822c4'
down_revision = 'cefb826a201b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('findings', 'recommendation_task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('findings_recommendation_task_id_fkey', 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'recommendation_task', ['recommendation_task_id'], ['id'], ondelete='CASCADE')
    op.add_column('recommendations', sa.Column('recommendation_task_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recommendations', 'recommendation_task', ['recommendation_task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_column('recommendations', 'recommendation_task_id')
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key('findings_recommendation_task_id_fkey', 'findings', 'recommendation_task', ['recommendation_task_id'], ['id'])
    op.alter_column('findings', 'recommendation_task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###