"""on_delete_aggregated

Revision ID: cae76af4e118
Revises: 06253ed3ac28
Create Date: 2024-07-26 19:17:05.829930

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import db


# revision identifiers, used by Alembic.
revision = 'cae76af4e118'
down_revision = '06253ed3ac28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('findings_aggregated_association_finding_id_fkey', 'findings_aggregated_association', type_='foreignkey')
    op.drop_constraint('findings_aggregated_associati_aggregated_recommendation_id_fkey', 'findings_aggregated_association', type_='foreignkey')
    op.create_foreign_key(None, 'findings_aggregated_association', 'findings', ['finding_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'findings_aggregated_association', 'aggregated_recommendations', ['aggregated_recommendation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'findings_aggregated_association', type_='foreignkey')
    op.drop_constraint(None, 'findings_aggregated_association', type_='foreignkey')
    op.create_foreign_key('findings_aggregated_associati_aggregated_recommendation_id_fkey', 'findings_aggregated_association', 'aggregated_recommendations', ['aggregated_recommendation_id'], ['id'])
    op.create_foreign_key('findings_aggregated_association_finding_id_fkey', 'findings_aggregated_association', 'findings', ['finding_id'], ['id'])
    # ### end Alembic commands ###