"""add_more_tables

Revision ID: cefb826a201b
Revises: 185c84d3b55c
Create Date: 2024-06-11 16:35:11.382657

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import models
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cefb826a201b'
down_revision = '185c84d3b55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_task',
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('findings', sa.Column('title_list', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('description_list', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('locations_list', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('cwe_id_list', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('cve_id_list', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('language', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('recommendation_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'findings', 'recommendation_task', ['recommendation_task_id'], ['id'])
    op.drop_column('findings', 'cve')
    op.drop_column('findings', 'content')
    op.drop_column('findings', 'finding')
    op.add_column('recommendations', sa.Column('description_short', sa.String(), nullable=True))
    op.add_column('recommendations', sa.Column('description_long', sa.String(), nullable=True))
    op.drop_column('recommendations', 'recommendation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('recommendation', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('recommendations', 'description_long')
    op.drop_column('recommendations', 'description_short')
    op.add_column('findings', sa.Column('finding', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('findings', sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('findings', sa.Column('cve', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.drop_column('findings', 'recommendation_task_id')
    op.drop_column('findings', 'language')
    op.drop_column('findings', 'severity')
    op.drop_column('findings', 'cve_id_list')
    op.drop_column('findings', 'cwe_id_list')
    op.drop_column('findings', 'locations_list')
    op.drop_column('findings', 'description_list')
    op.drop_column('findings', 'title_list')
    op.drop_table('recommendation_task')
    # ### end Alembic commands ###