"""add category

Revision ID: df4b7ee858c9
Revises: 5a77a313df99
Create Date: 2024-06-13 16:40:33.107426

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import db


# revision identifiers, used by Alembic.
revision = "df4b7ee858c9"
down_revision = "5a77a313df99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recommendations", sa.Column("category", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recommendations", "category")
    # ### end Alembic commands ###
