"""add title

Revision ID: e12b06b380db
Revises: 7d202c07bc94
Create Date: 2024-07-04 23:45:44.813153

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import db


# revision identifiers, used by Alembic.
revision = 'e12b06b380db'
down_revision = '7d202c07bc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('title', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'description')
    op.drop_column('findings', 'title')
    # ### end Alembic commands ###