name: API Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install

      - name: Generate docs
        run: |
          pipenv run python src/extract-docs.py

      - name: Save docs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: .docs
          if-no-files-found: error
