name: API Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install

      - name: Generate docs
        run: |
          pipenv run python src/extract-docs.py

      - name: Save docs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: .docs
          if-no-files-found: error

      - name: Generate API Endpoints
        id: generate-api-endpoints
        run: |
          echo "ENDPOINTS=$(pipenv run python src/generate-api-endpoints.py)" >> "$GITHUB_OUTPUT"

      - name: Comment PR on Success
        if: github.event_name == 'pull_request' && steps.generate-api-endpoints.outcome == 'success'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            # 🚀 Generated API Endpoints

            ```
            ${{ steps.generate-api-endpoints.outputs.ENDPOINTS }}
            ```
