name: License Compliance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  license-compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Check licenses
        run: |
          . venv/bin/activate
          pip install pip-licenses
          pip-licenses --from=mixed --output-file=dependencies_licenses.txt

      - name: Upload license reports
        uses: actions/upload-artifact@v3
        with:
          name: dependencies-license-reports
          path: dependencies_licenses.txt

      - name: License compliance summary
        run: echo "License compliance check completed. See artifacts for details."
